export const DISPLAY_ALERT = 'SHOW_ALERT'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_BOOKING_BEGIN = 'CREATE_BOOKING_BEGIN'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_ERROR = 'CREATE_BOOKING_ERROR'

export const GET_BOOKINGS_BEGIN = 'GET_BOOKINGS_BEGIN'
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS'

export const DELETE_BOOKING_BEGIN = 'DELETE_BOOKING_BEGIN'


export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'